[LuaTween0]
Measure=Script
ScriptFile=#@#Addons\LuaTween\Main.lua
TweenGroup=Tweenable
DynamicVariables=1
UpdateDivider=1
Tween0=Single | ThemeBase0 | X | #BaseXStart# | (#Outline#) | #TweenSpeed#
Tween1=Single | ThemePreview0 | X | (#BaseXStart#+(#Offset#/2)) | (#Outline#+(#Offset#/2)) | #TweenSpeed#
Tween2=Single | ThemeText0 | X | (#BaseXStart#+#ItemWidth#-#PictureWidth#-(#Offset#/2)) | (#ItemWidth#-#PictureWidth#-(#Offset#/2)) | #TweenSpeed#