[ThemeText0]
Meter=String
W=(#ItemWidth#-#PictureWidth#-#Offset#-(#Offset#/2))
H=(#ItemHeight#-#Offset#)
X=(#BaseXStart#+#ItemWidth#-#PictureWidth#-(#Offset#/2))
Y=(#ItemHeight#+#ItemSpacing#)r
Text=#Theme0Name#
FontSize=#FontSize#
FontColor=#Theme0TextColor#
FontFace=#FontStyle#
FontWeight=700
AntiAlias=1
StringAlign=CenterCenter
ClipString=2
Group=Content | Tweenable
Container=ThemeContainer
DynamicVariables=1
MouseActionCursor=0